version: '3'
services:
  posleydb:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ./wallet_api  # Path to the directory containing Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 wallet_api.wsgi:application
    volumes:
      - ./wallet_api:/app
    ports:
      - "8000:8000"
    depends_on:
      - posleydb
    env_file:
      - .env

volumes:
  postgres_data:
